import{a as f,i as c,S as g}from"./assets/vendor-CBMFibU3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const y="55171799-755350edf6c0ed064d9a514af",h=f.defaults.baseURL="https://pixabay.com/api/";function L(r){return f.get(h,{params:{key:`${y}`,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const d=document.querySelector(".gallery-list");function b(r){const o=r==null?void 0:r.map(s=>{const{webformatURL:a,largeImageURL:e,tags:t,likes:i,views:l,comments:p,downloads:u}=s;return`<li class='gallery-item'>
        <a class='gallery-link' href='${e}'>
          <img class='gallery-image' src='${a}' alt='${t}'>
        </a>
        <div class='image-description-wrapper'>
          <p class='image-text-info'>Likes <span class='additional-text-info'>${i}</span></p>
          <p class='image-text-info'>Views <span class='additional-text-info'>${l}</span></p>
          <p class='image-text-info'>Comments <span class='additional-text-info'>${p}</span></p>
          <p class='image-text-info'>Downloads <span class='additional-text-info'>${u}</span></p>
        </div>
      </li>`}).join("");d.insertAdjacentHTML("afterbegin",o)}function x(){d.innerHTML=""}const m=document.querySelector(".loader");function w(){m.classList.remove("is-hidden")}function v(){m.classList.add("is-hidden")}const n=document.querySelector(".form");n.addEventListener("submit",r=>{r.preventDefault();const o=n.elements["search-text"].value.trim();if(o===""){c.show({message:"Search field cannot be empty!",messageColor:"#fff",backgroundColor:"#ffa000",position:"topRight",icon:"bi bi-exclamation-triangle",iconColor:"#fff"});return}x(),w(),L(o).then(s=>{if(s.data.hits.length===0)c.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"});else{b(s.data.hits);const a=document.querySelectorAll(".gallery-image"),e=Array.from(a).map(t=>new Promise((i,l)=>{}));Promise.allSettled(e).then(),new g(".gallery-link",{overlayOpacity:.8,captionDelay:250,captionsData:"alt"}).refresh()}}).catch(s=>console.log(s)).finally(()=>{v(),n.reset()})});
//# sourceMappingURL=index.js.map
