import{a as f,i as d,S as y}from"./assets/vendor-CBMFibU3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g="55171799-755350edf6c0ed064d9a514af",h=f.defaults.baseURL="https://pixabay.com/api/";function L(r){return f.get(h,{params:{key:`${g}`,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const n=document.querySelector(".gallery-list");function b(r){const o=r==null?void 0:r.map(s=>{const{webformatURL:i,largeImageURL:e,tags:t,likes:a,views:c,comments:p,downloads:u}=s;return`<li class='gallery-item'>
        <a class='gallery-link' href='${e}'>
          <img class='gallery-image' src='${i}' alt='${t}'>
        </a>
        <div class='image-description-wrapper'>
          <p class='image-text-info'>Likes <span class='additional-text-info'>${a}</span></p>
          <p class='image-text-info'>Views <span class='additional-text-info'>${c}</span></p>
          <p class='image-text-info'>Comments <span class='additional-text-info'>${p}</span></p>
          <p class='image-text-info'>Downloads <span class='additional-text-info'>${u}</span></p>
        </div>
      </li>`}).join("");n.insertAdjacentHTML("afterbegin",o)}function x(){n.innerHTML=""}const m=document.querySelector(".loader");function w(){n.style.display="none",m.classList.remove("is-hidden")}function v(){m.classList.add("is-hidden"),n.style.display="flex"}const l=document.querySelector(".form");l.addEventListener("submit",r=>{r.preventDefault();const o=l.elements["search-text"].value.trim();if(o===""){d.show({message:"Search field cannot be empty!",messageColor:"#fff",backgroundColor:"#ffa000",position:"topRight",icon:"bi bi-exclamation-triangle",iconColor:"#fff"});return}x(),L(o).then(s=>{if(s.data.hits.length===0)d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"});else{w(),b(s.data.hits);const i=document.querySelectorAll(".gallery-image"),e=Array.from(i).map(t=>new Promise((a,c)=>{t.addEventListener("load",()=>{a(t)}),t.addEventListener("error",()=>{a(t)})}));Promise.allSettled(e).then(()=>{v(),new y(".gallery-link",{overlayOpacity:.8,captionDelay:250,captionsData:"alt"}).refresh()})}}).catch(s=>(console.log(s.message),Promise.reject(s))).finally(()=>{l.reset()})});
//# sourceMappingURL=index.js.map
