import{a as f,i as c,S as g}from"./assets/vendor-CBMFibU3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const h="55171799-755350edf6c0ed064d9a514af",L=f.defaults.baseURL="https://pixabay.com/api/";function b(r){return f.get(L,{params:{key:`${h}`,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const p=document.querySelector(".gallery-list");function x(r){const o=r==null?void 0:r.map(s=>{const{webformatURL:i,largeImageURL:e,tags:t,likes:a,views:l,comments:m,downloads:y}=s;return`<li class='gallery-item'>
        <a class='gallery-link' href='${e}'>
          <img class='gallery-image' src='${i}' alt='${t}'>
        </a>
        <div class='image-description-wrapper'>
          <p class='image-text-info'>Likes <span class='additional-text-info'>${a}</span></p>
          <p class='image-text-info'>Views <span class='additional-text-info'>${l}</span></p>
          <p class='image-text-info'>Comments <span class='additional-text-info'>${m}</span></p>
          <p class='image-text-info'>Downloads <span class='additional-text-info'>${y}</span></p>
        </div>
      </li>`}).join("");p.insertAdjacentHTML("afterbegin",o)}function w(){p.innerHTML=""}const u=document.querySelector(".loader");function S(){u.classList.remove("is-hidden")}function v(){u.classList.add("is-hidden")}const n=document.querySelector(".form"),d=document.querySelector(".gallery-list");n.addEventListener("submit",r=>{r.preventDefault();const o=n.elements["search-text"].value.trim();if(o===""){c.show({message:"Search field cannot be empty!",messageColor:"#fff",backgroundColor:"#ffa000",position:"topRight",icon:"bi bi-exclamation-triangle",iconColor:"#fff"});return}w(),b(o).then(s=>{if(s.data.hits.length===0)c.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"});else{S(),d.style.display="none",x(s.data.hits);const i=document.querySelectorAll(".gallery-image"),e=Array.from(i).map(t=>new Promise((a,l)=>{t.addEventListener("load",()=>{a(t)}),t.addEventListener("error",()=>{a(t)})}));Promise.allSettled(e).then(()=>{v(),d.style.display="flex",new g(".gallery-link",{overlayOpacity:.8,captionDelay:250,captionsData:"alt"}).refresh()})}}).catch(s=>console.log(s)).finally(()=>{n.reset()})});
//# sourceMappingURL=index.js.map
